// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8ef2eed7-ea66-4a66-b5e1-e2dabe5268da",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_aedLyFgTA",
    "aws_user_pools_web_client_id": "1o42s0obamcdff6mqduq1tur35",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://oppui5mppzbh7nbqanfthrvhsi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
